import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { detectRepository, formatDetectionMarkdown } from "../skills/security-audit/scripts/detect-stack.mjs";
import { STACK_CATALOG } from "../skills/security-audit/scripts/stack-catalog.mjs";
import { VERSION } from "./version.mjs";

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));
const sourceSkillDirectory = path.resolve(moduleDirectory, "../skills/security-audit");

async function pathExists(filename) {
  try {
    await fs.access(filename);
    return true;
  } catch {
    return false;
  }
}

async function isManagedSkill(directory) {
  try {
    const manifest = JSON.parse(await fs.readFile(path.join(directory, "compiler-manifest.json"), "utf8"));
    return manifest.compiler === "security-skill-compiler";
  } catch {
    return false;
  }
}

async function replaceDirectory(stagedDirectory, destination, force) {
  const exists = await pathExists(destination);
  if (exists && !force && !(await isManagedSkill(destination))) {
    throw new Error(`Refusing to overwrite unmanaged skill at ${destination}; pass --force to replace it`);
  }

  await fs.mkdir(path.dirname(destination), { recursive: true });
  if (!exists) {
    await fs.rename(stagedDirectory, destination);
    return;
  }

  const backup = `${destination}.backup-${process.pid}-${Date.now()}`;
  await fs.rename(destination, backup);
  try {
    await fs.rename(stagedDirectory, destination);
    await fs.rm(backup, { recursive: true, force: true });
  } catch (error) {
    if (await pathExists(destination)) await fs.rm(destination, { recursive: true, force: true });
    await fs.rename(backup, destination);
    throw error;
  }
}

export async function compileSkill(options = {}) {
  const targetRoot = path.resolve(options.targetRoot ?? process.cwd());
  const outputRoot = path.resolve(options.outputRoot ?? path.join(targetRoot, ".security-skill-compiler", "skills"));
  const targetStat = await fs.stat(targetRoot).catch(() => null);
  if (!targetStat?.isDirectory()) throw new Error(`Target is not a directory: ${targetRoot}`);

  const detection = options.detection ?? await detectRepository(targetRoot, { maxFiles: options.maxFiles });
  const destination = path.join(outputRoot, "security-audit");
  const stagedDirectory = path.join(outputRoot, `.security-audit.stage-${process.pid}-${Date.now()}`);

  await fs.mkdir(outputRoot, { recursive: true });
  await fs.cp(sourceSkillDirectory, stagedDirectory, { recursive: true, force: true });

  const selected = new Set(detection.stacks.map((stack) => stack.id));
  if (selected.size > 0) {
    for (const stack of STACK_CATALOG) {
      if (!selected.has(stack.id)) {
        await fs.rm(path.join(stagedDirectory, stack.reference), { force: true });
      }
    }
  }

  const profile = `${formatDetectionMarkdown(detection)}\n<!-- generated by security-skill-compiler ${VERSION} -->\n`;
  const manifest = {
    compiler: "security-skill-compiler",
    compilerVersion: VERSION,
    schemaVersion: 1,
    target: ".",
    primaryStack: detection.primaryStack,
    stacks: detection.stacks.map(({ id, confidence, frameworks, reference }) => ({ id, confidence, frameworks, reference }))
  };

  await fs.writeFile(path.join(stagedDirectory, "STACK_PROFILE.md"), profile, "utf8");
  await fs.writeFile(path.join(stagedDirectory, "compiler-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  try {
    await replaceDirectory(stagedDirectory, destination, options.force === true);
  } catch (error) {
    await fs.rm(stagedDirectory, { recursive: true, force: true });
    throw error;
  }

  return { destination, detection, manifest };
}
